<header class="header">
  <div class="header__inner">
    <a href="#" class="header__logo">SINGLEX Platform</a>
    <ul class="header__gnb gnb">
      <li class="gnb__item">
        <a href="#" class="gnb__link is_active">요금 청구서</a>
      </li>
      <li class="gnb__item">
        <a href="#" class="gnb__link">계약조회</a>
      </li>
      <li class="gnb__item">
        <a href="#" class="gnb__link">계약담당자 관리</a>
      </li>
      <li class="gnb__item gnb__item--single">
        <a href="#" class="gnb__link">SINGLEX Town</a>
      </li>
    </ul>
    <div class="header__info">
      <strong class="name">김이름</strong>
      <i class="profile"></i>
    </div>
  </div>
</header>
